//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinanceTracker.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalFinanceTracker.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建账本.
        /// </summary>
        public static string Btn_AddBook {
            get {
                return ResourceManager.GetString("Btn_AddBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        public static string Btn_Confirm {
            get {
                return ResourceManager.GetString("Btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑此账户.
        /// </summary>
        public static string Btn_EditAccount {
            get {
                return ResourceManager.GetString("Btn_EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支出.
        /// </summary>
        public static string Btn_Expense {
            get {
                return ResourceManager.GetString("Btn_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收入.
        /// </summary>
        public static string Btn_Income {
            get {
                return ResourceManager.GetString("Btn_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 余额调整.
        /// </summary>
        public static string Category_BalanceAdjust {
            get {
                return ResourceManager.GetString("Category_BalanceAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖金.
        /// </summary>
        public static string Category_Bonus {
            get {
                return ResourceManager.GetString("Category_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数码.
        /// </summary>
        public static string Category_Digital {
            get {
                return ResourceManager.GetString("Category_Digital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教育.
        /// </summary>
        public static string Category_Education {
            get {
                return ResourceManager.GetString("Category_Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 娱乐.
        /// </summary>
        public static string Category_Entertainment {
            get {
                return ResourceManager.GetString("Category_Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 饮食.
        /// </summary>
        public static string Category_Food {
            get {
                return ResourceManager.GetString("Category_Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 医疗.
        /// </summary>
        public static string Category_Medical {
            get {
                return ResourceManager.GetString("Category_Medical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工资.
        /// </summary>
        public static string Category_Salary {
            get {
                return ResourceManager.GetString("Category_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 购物.
        /// </summary>
        public static string Category_Shopping {
            get {
                return ResourceManager.GetString("Category_Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交通.
        /// </summary>
        public static string Category_Transport {
            get {
                return ResourceManager.GetString("Category_Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将记一笔{0}：{1}.
        /// </summary>
        public static string Dialog_AdjustmentPreview {
            get {
                return ResourceManager.GetString("Dialog_AdjustmentPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 余额已更新！.
        /// </summary>
        public static string Dialog_BalanceUpdated {
            get {
                return ResourceManager.GetString("Dialog_BalanceUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        public static string Dialog_Confirm {
            get {
                return ResourceManager.GetString("Dialog_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前：.
        /// </summary>
        public static string Dialog_Current {
            get {
                return ResourceManager.GetString("Dialog_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑此账户.
        /// </summary>
        public static string Dialog_EditAccountTitle {
            get {
                return ResourceManager.GetString("Dialog_EditAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入新的用户名。.
        /// </summary>
        public static string Dialog_EditUsernamePrompt {
            get {
                return ResourceManager.GetString("Dialog_EditUsernamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改用户名.
        /// </summary>
        public static string Dialog_EditUsernameTitle {
            get {
                return ResourceManager.GetString("Dialog_EditUsernameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入新的余额：.
        /// </summary>
        public static string Dialog_EnterNewBalance {
            get {
                return ResourceManager.GetString("Dialog_EnterNewBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string Dialog_Error {
            get {
                return ResourceManager.GetString("Dialog_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发生未知错误，请稍后重试。.
        /// </summary>
        public static string Dialog_GenericError {
            get {
                return ResourceManager.GetString("Dialog_GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入有效的金额。.
        /// </summary>
        public static string Dialog_InvalidAmount {
            get {
                return ResourceManager.GetString("Dialog_InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string Dialog_OK {
            get {
                return ResourceManager.GetString("Dialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择头像.
        /// </summary>
        public static string Dialog_PickerTitle {
            get {
                return ResourceManager.GetString("Dialog_PickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Dialog_Save {
            get {
                return ResourceManager.GetString("Dialog_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信息已保存。.
        /// </summary>
        public static string Dialog_SaveSuccessMsg {
            get {
                return ResourceManager.GetString("Dialog_SaveSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功.
        /// </summary>
        public static string Dialog_SaveSuccessTitle {
            get {
                return ResourceManager.GetString("Dialog_SaveSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功.
        /// </summary>
        public static string Dialog_Success {
            get {
                return ResourceManager.GetString("Dialog_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Dialog_Tip {
            get {
                return ResourceManager.GetString("Dialog_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户名称.
        /// </summary>
        public static string Entry_AccountName {
            get {
                return ResourceManager.GetString("Entry_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入新账本名字....
        /// </summary>
        public static string Entry_Book {
            get {
                return ResourceManager.GetString("Entry_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入预算....
        /// </summary>
        public static string Entry_Budget {
            get {
                return ResourceManager.GetString("Entry_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击写备注....
        /// </summary>
        public static string Entry_Note {
            get {
                return ResourceManager.GetString("Entry_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期初余额（可选）.
        /// </summary>
        public static string Entry_OpeningEntry {
            get {
                return ResourceManager.GetString("Entry_OpeningEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你好，{0}！.
        /// </summary>
        public static string Hello_User {
            get {
                return ResourceManager.GetString("Hello_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户.
        /// </summary>
        public static string Label_Account {
            get {
                return ResourceManager.GetString("Label_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加账户.
        /// </summary>
        public static string Label_AddAccount {
            get {
                return ResourceManager.GetString("Label_AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有账户.
        /// </summary>
        public static string Label_AllAccounts {
            get {
                return ResourceManager.GetString("Label_AllAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金额.
        /// </summary>
        public static string Label_Amount {
            get {
                return ResourceManager.GetString("Label_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结余.
        /// </summary>
        public static string Label_Balance {
            get {
                return ResourceManager.GetString("Label_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收支差额.
        /// </summary>
        public static string Label_BalanceDiff {
            get {
                return ResourceManager.GetString("Label_BalanceDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账本.
        /// </summary>
        public static string Label_Book {
            get {
                return ResourceManager.GetString("Label_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账本列表.
        /// </summary>
        public static string Label_BookList {
            get {
                return ResourceManager.GetString("Label_BookList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预算.
        /// </summary>
        public static string Label_Budget {
            get {
                return ResourceManager.GetString("Label_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用途.
        /// </summary>
        public static string Label_Category {
            get {
                return ResourceManager.GetString("Label_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前账本：.
        /// </summary>
        public static string Label_CurrentBook {
            get {
                return ResourceManager.GetString("Label_CurrentBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除账户.
        /// </summary>
        public static string Label_DeleteAccount {
            get {
                return ResourceManager.GetString("Label_DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要删除此账户？.
        /// </summary>
        public static string Label_DeleteAccountAlert {
            get {
                return ResourceManager.GetString("Label_DeleteAccountAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同时删除该账户所有明细记录.
        /// </summary>
        public static string Label_DeleteAccountAllDetail {
            get {
                return ResourceManager.GetString("Label_DeleteAccountAllDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无记录....
        /// </summary>
        public static string Label_EmptyList {
            get {
                return ResourceManager.GetString("Label_EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支出.
        /// </summary>
        public static string Label_Expense {
            get {
                return ResourceManager.GetString("Label_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收入.
        /// </summary>
        public static string Label_Income {
            get {
                return ResourceManager.GetString("Label_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 过去4个月的总资产趋势.
        /// </summary>
        public static string Label_Last4MonthsTrend {
            get {
                return ResourceManager.GetString("Label_Last4MonthsTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最近修改时间.
        /// </summary>
        public static string Label_LastModified {
            get {
                return ResourceManager.GetString("Label_LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本月预算.
        /// </summary>
        public static string Label_MonthBudget {
            get {
                return ResourceManager.GetString("Label_MonthBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 明细（按月份）.
        /// </summary>
        public static string Label_MonthDetail {
            get {
                return ResourceManager.GetString("Label_MonthDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本月支出.
        /// </summary>
        public static string Label_MonthExpense {
            get {
                return ResourceManager.GetString("Label_MonthExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本月收入.
        /// </summary>
        public static string Label_MonthIncome {
            get {
                return ResourceManager.GetString("Label_MonthIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本月收支平衡情况.
        /// </summary>
        public static string Label_MonthlySummary {
            get {
                return ResourceManager.GetString("Label_MonthlySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本月还没有记录....
        /// </summary>
        public static string Label_NoMonthlyRecords {
            get {
                return ResourceManager.GetString("Label_NoMonthlyRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注.
        /// </summary>
        public static string Label_Note {
            get {
                return ResourceManager.GetString("Label_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人.
        /// </summary>
        public static string Label_Personal {
            get {
                return ResourceManager.GetString("Label_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账单.
        /// </summary>
        public static string Label_Record {
            get {
                return ResourceManager.GetString("Label_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今日收支.
        /// </summary>
        public static string Label_TodayList {
            get {
                return ResourceManager.GetString("Label_TodayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总金额: .
        /// </summary>
        public static string Label_TotalAmount {
            get {
                return ResourceManager.GetString("Label_TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总资产: .
        /// </summary>
        public static string Label_TotalAssets {
            get {
                return ResourceManager.GetString("Label_TotalAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账单总览.
        /// </summary>
        public static string Label_ViewRecord {
            get {
                return ResourceManager.GetString("Label_ViewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择账户.
        /// </summary>
        public static string Picker_ChooseAccount {
            get {
                return ResourceManager.GetString("Picker_ChooseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择月份.
        /// </summary>
        public static string Picker_ChooseMonth {
            get {
                return ResourceManager.GetString("Picker_ChooseMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择货币.
        /// </summary>
        public static string Picker_Currency {
            get {
                return ResourceManager.GetString("Picker_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择语言.
        /// </summary>
        public static string Picker_Language {
            get {
                return ResourceManager.GetString("Picker_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加.
        /// </summary>
        public static string Toolbar_Add {
            get {
                return ResourceManager.GetString("Toolbar_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string Toolbar_Refresh {
            get {
                return ResourceManager.GetString("Toolbar_Refresh", resourceCulture);
            }
        }
    }
}
